name: CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.4

    - name: Creates virtual environment
      run: |
        make create_venv

    - name: Install dependencies
      run: |
        make install

    - name: Run tests
      run: |
        make test_cloud
        
    - name: Cleans up virtual environment
      run: |
        make test_clean
